/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import model.Categoria;
import model.Cliente;
import model.Producto;
import model.Proveedor;
import controller.CategoriaController;
import controller.ClienteController;
import controller.ProductoController;
import controller.ProveedorController;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;


public class FormularioCategoria extends javax.swing.JFrame {

  
    public FormularioCategoria() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        CategoriaCrearBtn = new javax.swing.JButton();
        txtIdCategoria = new javax.swing.JTextField();
        txtnombrecategoria = new javax.swing.JTextField();
        CategoriaLeerBtn = new javax.swing.JButton();
        CategoriaActualizarBtn = new javax.swing.JButton();
        CategoriaEliminarBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbTotalCategorias = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        crearproducto = new javax.swing.JButton();
        idproductofield = new javax.swing.JTextField();
        nombreproductofield = new javax.swing.JTextField();
        leerproducto = new javax.swing.JButton();
        actualizarproducto = new javax.swing.JButton();
        eliminarproducto = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        idcategoriaproductofield = new javax.swing.JTextField();
        precioproductofield = new javax.swing.JTextField();
        jScrollPane8 = new javax.swing.JScrollPane();
        tablaproducto = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        crearcliente = new javax.swing.JButton();
        idclientefield = new javax.swing.JTextField();
        nombreclientefield = new javax.swing.JTextField();
        leercliente = new javax.swing.JButton();
        actualizarcliente = new javax.swing.JButton();
        eliminarcliente = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        clientetabla = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        crearproveedor = new javax.swing.JButton();
        idproveedorfield = new javax.swing.JTextField();
        nombreproveedorfield = new javax.swing.JTextField();
        leerproveedor = new javax.swing.JButton();
        actualizarproveedor = new javax.swing.JButton();
        eliminarproveedor = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        proveedortabla = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        precioproveedorfield = new javax.swing.JTextField();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        CategoriaCrearBtn.setBackground(new java.awt.Color(0, 204, 204));
        CategoriaCrearBtn.setText("Crear");
        CategoriaCrearBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CategoriaCrearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CategoriaCrearBtnActionPerformed(evt);
            }
        });

        txtIdCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdCategoriaActionPerformed(evt);
            }
        });

        txtnombrecategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnombrecategoriaActionPerformed(evt);
            }
        });

        CategoriaLeerBtn.setBackground(new java.awt.Color(0, 204, 204));
        CategoriaLeerBtn.setText("Leer");
        CategoriaLeerBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CategoriaLeerBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CategoriaLeerBtnMouseClicked(evt);
            }
        });
        CategoriaLeerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CategoriaLeerBtnActionPerformed(evt);
            }
        });

        CategoriaActualizarBtn.setBackground(new java.awt.Color(0, 204, 204));
        CategoriaActualizarBtn.setText("Actualizar");
        CategoriaActualizarBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CategoriaActualizarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CategoriaActualizarBtnActionPerformed(evt);
            }
        });

        CategoriaEliminarBtn.setBackground(new java.awt.Color(0, 204, 204));
        CategoriaEliminarBtn.setText("Eliminar");
        CategoriaEliminarBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CategoriaEliminarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CategoriaEliminarBtnActionPerformed(evt);
            }
        });

        jLabel4.setText("Id.");

        jLabel5.setText("Nombre");

        tbTotalCategorias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CategoriaId", "Nombre"
            }
        ));
        jScrollPane4.setViewportView(tbTotalCategorias);
        if (tbTotalCategorias.getColumnModel().getColumnCount() > 0) {
            tbTotalCategorias.getColumnModel().getColumn(1).setHeaderValue("Nombre");
        }

        jLabel6.setText("¿Qué desea hacer en categorias?");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(txtIdCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CategoriaCrearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtnombrecategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(CategoriaLeerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(CategoriaEliminarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(43, 43, 43)
                        .addComponent(CategoriaActualizarBtn)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CategoriaActualizarBtn)
                    .addComponent(CategoriaLeerBtn)
                    .addComponent(CategoriaEliminarBtn)
                    .addComponent(CategoriaCrearBtn))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtnombrecategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtIdCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 716, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 344, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Categoria", jPanel2);

        crearproducto.setBackground(new java.awt.Color(0, 204, 204));
        crearproducto.setText("Crear");
        crearproducto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        crearproducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearproductoActionPerformed(evt);
            }
        });

        idproductofield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idproductofieldActionPerformed(evt);
            }
        });

        nombreproductofield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreproductofieldActionPerformed(evt);
            }
        });

        leerproducto.setBackground(new java.awt.Color(0, 204, 204));
        leerproducto.setText("Leer");
        leerproducto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        leerproducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                leerproductoMouseClicked(evt);
            }
        });
        leerproducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leerproductoActionPerformed(evt);
            }
        });

        actualizarproducto.setBackground(new java.awt.Color(0, 204, 204));
        actualizarproducto.setText("Actualizar");
        actualizarproducto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        actualizarproducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarproductoActionPerformed(evt);
            }
        });

        eliminarproducto.setBackground(new java.awt.Color(0, 204, 204));
        eliminarproducto.setText("Eliminar");
        eliminarproducto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        eliminarproducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarproductoActionPerformed(evt);
            }
        });

        jLabel18.setText("Id.");

        jLabel19.setText("Nombre");

        jLabel20.setText("¿Qué desea hacer en Producto?");

        jLabel21.setText("Precio");

        jLabel22.setText("Id de la categoria a la que pertenece");

        idcategoriaproductofield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idcategoriaproductofieldActionPerformed(evt);
            }
        });

        precioproductofield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                precioproductofieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(leerproducto, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(eliminarproducto, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(43, 43, 43)
                        .addComponent(actualizarproducto))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel22))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addGap(27, 27, 27)
                                .addComponent(idproductofield, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                    .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(precioproductofield, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel6Layout.createSequentialGroup()
                                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel6Layout.createSequentialGroup()
                                            .addGap(50, 50, 50)
                                            .addComponent(crearproducto, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel6Layout.createSequentialGroup()
                                            .addGap(65, 65, 65)
                                            .addComponent(idcategoriaproductofield, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(73, 73, 73)))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nombreproductofield, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(165, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(actualizarproducto)
                    .addComponent(leerproducto)
                    .addComponent(eliminarproducto)
                    .addComponent(crearproducto))
                .addGap(30, 30, 30)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreproductofield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idproductofield, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(precioproductofield, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(idcategoriaproductofield, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        tablaproducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Producto id", "Nombre", "Precio", "Categoria Id"
            }
        ));
        jScrollPane8.setViewportView(tablaproducto);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(273, 273, 273)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Producto", jPanel4);

        crearcliente.setBackground(new java.awt.Color(0, 204, 204));
        crearcliente.setText("Crear");
        crearcliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        crearcliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearclienteActionPerformed(evt);
            }
        });

        idclientefield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idclientefieldActionPerformed(evt);
            }
        });

        nombreclientefield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreclientefieldActionPerformed(evt);
            }
        });

        leercliente.setBackground(new java.awt.Color(0, 204, 204));
        leercliente.setText("Leer");
        leercliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        leercliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                leerclienteMouseClicked(evt);
            }
        });
        leercliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leerclienteActionPerformed(evt);
            }
        });

        actualizarcliente.setBackground(new java.awt.Color(0, 204, 204));
        actualizarcliente.setText("Actualizar");
        actualizarcliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        actualizarcliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarclienteActionPerformed(evt);
            }
        });

        eliminarcliente.setBackground(new java.awt.Color(0, 204, 204));
        eliminarcliente.setText("Eliminar");
        eliminarcliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        eliminarcliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarclienteActionPerformed(evt);
            }
        });

        jLabel13.setText("Id.");

        jLabel14.setText("Nombre");

        clientetabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id cliente", "Nombre"
            }
        ));
        jScrollPane7.setViewportView(clientetabla);
        if (clientetabla.getColumnModel().getColumnCount() > 0) {
            clientetabla.getColumnModel().getColumn(1).setHeaderValue("Nombre");
        }

        jLabel15.setText("¿Qué desea hacer en Clientes?");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(18, 18, 18)
                                .addComponent(idclientefield, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(crearcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nombreclientefield, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(leercliente, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(eliminarcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(43, 43, 43)
                        .addComponent(actualizarcliente)
                        .addGap(0, 171, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(actualizarcliente)
                    .addComponent(leercliente)
                    .addComponent(eliminarcliente)
                    .addComponent(crearcliente))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(nombreclientefield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(idclientefield, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)))
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Cliente", jPanel5);

        crearproveedor.setBackground(new java.awt.Color(0, 204, 204));
        crearproveedor.setText("Crear");
        crearproveedor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        crearproveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearproveedorActionPerformed(evt);
            }
        });

        idproveedorfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idproveedorfieldActionPerformed(evt);
            }
        });

        nombreproveedorfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreproveedorfieldActionPerformed(evt);
            }
        });

        leerproveedor.setBackground(new java.awt.Color(0, 204, 204));
        leerproveedor.setText("Leer");
        leerproveedor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        leerproveedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                leerproveedorMouseClicked(evt);
            }
        });
        leerproveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leerproveedorActionPerformed(evt);
            }
        });

        actualizarproveedor.setBackground(new java.awt.Color(0, 204, 204));
        actualizarproveedor.setText("Actualizar");
        actualizarproveedor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        actualizarproveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarproveedorActionPerformed(evt);
            }
        });

        eliminarproveedor.setBackground(new java.awt.Color(0, 204, 204));
        eliminarproveedor.setText("Eliminar");
        eliminarproveedor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        eliminarproveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarproveedorActionPerformed(evt);
            }
        });

        jLabel1.setText("Id.");

        jLabel2.setText("Nombre");

        proveedortabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id proveedor", "Nombre", "Precio"
            }
        ));
        jScrollPane3.setViewportView(proveedortabla);

        jLabel3.setText("¿Qué desea hacer en categorias?");

        jLabel7.setText("Precio");

        precioproveedorfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                precioproveedorfieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(crearproveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nombreproveedorfield, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel1))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(idproveedorfield, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(precioproveedorfield, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(leerproveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(eliminarproveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(43, 43, 43)
                        .addComponent(actualizarproveedor)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(actualizarproveedor)
                    .addComponent(leerproveedor)
                    .addComponent(eliminarproveedor)
                    .addComponent(crearproveedor))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nombreproveedorfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(idproveedorfield, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(precioproveedorfield, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Proveedor", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void eliminarproveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarproveedorActionPerformed
        ProveedorController proveedor= new ProveedorController();
        proveedor.eliminarProveedor(Integer.parseInt(idproveedorfield.getText()));
    }//GEN-LAST:event_eliminarproveedorActionPerformed

    private void actualizarproveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarproveedorActionPerformed
        ProveedorController proveedor= new ProveedorController();
        proveedor.actualizarProveedor(Integer.parseInt(idproveedorfield.getText()), nombreproveedorfield.getText(),Integer.parseInt(precioproveedorfield.getText()));
    }//GEN-LAST:event_actualizarproveedorActionPerformed

    private void leerproveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leerproveedorActionPerformed
        DefaultTableModel model = (DefaultTableModel) proveedortabla.getModel();
        model.setRowCount(0);
        ArrayList<Proveedor> proveedores = new ArrayList();
        ProveedorController proveedor = new ProveedorController();
        List<Proveedor> leer = proveedor.leerProveedor();
        proveedores.addAll(leer);

        Object columnas[] = new Object[3];
        for(Proveedor c : proveedores){
            columnas[0]=c.getId_proveedor();
            columnas [1]=c.getNombre();
            columnas [2]=c.getPrecio();
            model.addRow(columnas);
        }
    }//GEN-LAST:event_leerproveedorActionPerformed

    private void leerproveedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_leerproveedorMouseClicked

    }//GEN-LAST:event_leerproveedorMouseClicked

    private void nombreproveedorfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreproveedorfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreproveedorfieldActionPerformed

    private void idproveedorfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idproveedorfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idproveedorfieldActionPerformed

    private void crearproveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearproveedorActionPerformed
        ProveedorController proveedor= new ProveedorController();
        proveedor.crearProveedor(nombreproveedorfield.getText(),Integer.parseInt(precioproveedorfield.getText()));
    }//GEN-LAST:event_crearproveedorActionPerformed

    private void eliminarclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarclienteActionPerformed
        ClienteController cliente= new ClienteController();
        cliente.eliminarCliente(Integer.parseInt(idclientefield.getText()));
    }//GEN-LAST:event_eliminarclienteActionPerformed

    private void actualizarclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarclienteActionPerformed
        ClienteController cliente= new ClienteController();
        cliente.actualizarCliente(Integer.parseInt(idclientefield.getText()), nombreclientefield.getText());
    }//GEN-LAST:event_actualizarclienteActionPerformed

    private void leerclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leerclienteActionPerformed
       DefaultTableModel model = (DefaultTableModel) clientetabla.getModel();
        model.setRowCount(0);
        ArrayList<Cliente> clientes = new ArrayList();
        ClienteController cliente = new ClienteController();
        List<Cliente> leer = cliente.leerCliente();
        clientes.addAll(leer);

        Object columnas[] = new Object[2];
        for(Cliente c : clientes){
            columnas[0]=c.getId();
            columnas [1]=c.getNombre();
            model.addRow(columnas);
        } 
    }//GEN-LAST:event_leerclienteActionPerformed

    private void leerclienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_leerclienteMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_leerclienteMouseClicked

    private void idclientefieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idclientefieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idclientefieldActionPerformed

    private void nombreclientefieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreclientefieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreclientefieldActionPerformed

    private void crearclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearclienteActionPerformed
        ClienteController cliente= new ClienteController();
        cliente.crearCliente(nombreclientefield.getText());
    }//GEN-LAST:event_crearclienteActionPerformed

    private void crearproductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearproductoActionPerformed
        ProductoController producto= new ProductoController();
        producto.crearProducto(nombreproductofield.getText(),Integer.parseInt(precioproductofield.getText()),Integer.parseInt(idcategoriaproductofield.getText()));
    }//GEN-LAST:event_crearproductoActionPerformed

    private void idproductofieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idproductofieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idproductofieldActionPerformed

    private void nombreproductofieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreproductofieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreproductofieldActionPerformed

    private void leerproductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_leerproductoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_leerproductoMouseClicked

    private void leerproductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leerproductoActionPerformed
        DefaultTableModel model = (DefaultTableModel) tablaproducto.getModel();
        model.setRowCount(0);
        ArrayList<Producto> productos = new ArrayList();
        ProductoController producto = new ProductoController();
        List<Producto> leer = producto.leerProductos();
        productos.addAll(leer);

        Object columnas[] = new Object[4];
        for(Producto c : productos){
            columnas[0]=c.getId();
            columnas [1]=c.getNombre();
            columnas [2]=c.getPrecio();
            columnas [3]=c.getCategoria_id();
            model.addRow(columnas);
        }
    }//GEN-LAST:event_leerproductoActionPerformed

    private void actualizarproductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarproductoActionPerformed
        ProductoController producto= new ProductoController();
        producto.actualizarProducto(Integer.parseInt(idproductofield.getText()), nombreproductofield.getText(),Integer.parseInt(precioproductofield.getText()),Integer.parseInt(idcategoriaproductofield.getText()));
    }//GEN-LAST:event_actualizarproductoActionPerformed

    private void eliminarproductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarproductoActionPerformed
        ProductoController producto= new ProductoController();
        producto.eliminarProducto(Integer.parseInt(idproductofield.getText()));
    }//GEN-LAST:event_eliminarproductoActionPerformed

    private void idcategoriaproductofieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idcategoriaproductofieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idcategoriaproductofieldActionPerformed

    private void precioproductofieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_precioproductofieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_precioproductofieldActionPerformed

    private void CategoriaCrearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CategoriaCrearBtnActionPerformed
        CategoriaController categoria= new CategoriaController();
        categoria.crearCategoriaVista(txtnombrecategoria.getText());
    }//GEN-LAST:event_CategoriaCrearBtnActionPerformed

    private void txtIdCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdCategoriaActionPerformed

    private void txtnombrecategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnombrecategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombrecategoriaActionPerformed

    private void CategoriaLeerBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CategoriaLeerBtnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_CategoriaLeerBtnMouseClicked

    private void CategoriaLeerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CategoriaLeerBtnActionPerformed
        DefaultTableModel model = (DefaultTableModel) tbTotalCategorias.getModel();
        model.setRowCount(0);
        ArrayList<Categoria> categorias = new ArrayList();
        CategoriaController categoria = new CategoriaController();
        List<Categoria> leer = categoria.leerCategoriasVista();
        categorias.addAll(leer);

        Object columnas[] = new Object[2];
        for(Categoria c : categorias){
            columnas[0]=c.getCategoria_id();
            columnas [1]=c.getNombre();
            model.addRow(columnas);
        }
    }//GEN-LAST:event_CategoriaLeerBtnActionPerformed

    private void CategoriaActualizarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CategoriaActualizarBtnActionPerformed
        CategoriaController categoria= new CategoriaController();
        categoria.actualizarCategoriaVista(Integer.parseInt(txtIdCategoria.getText()), txtnombrecategoria.getText());
    }//GEN-LAST:event_CategoriaActualizarBtnActionPerformed

    private void CategoriaEliminarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CategoriaEliminarBtnActionPerformed
        CategoriaController categoria= new CategoriaController();
        categoria.eliminarCategoriaVista(Integer.parseInt(txtIdCategoria.getText()));
    }//GEN-LAST:event_CategoriaEliminarBtnActionPerformed

    private void precioproveedorfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_precioproveedorfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_precioproveedorfieldActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormularioCategoria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CategoriaActualizarBtn;
    private javax.swing.JButton CategoriaCrearBtn;
    private javax.swing.JButton CategoriaEliminarBtn;
    private javax.swing.JButton CategoriaLeerBtn;
    private javax.swing.JButton actualizarcliente;
    private javax.swing.JButton actualizarproducto;
    private javax.swing.JButton actualizarproveedor;
    private javax.swing.JTable clientetabla;
    private javax.swing.JButton crearcliente;
    private javax.swing.JButton crearproducto;
    private javax.swing.JButton crearproveedor;
    private javax.swing.JButton eliminarcliente;
    private javax.swing.JButton eliminarproducto;
    private javax.swing.JButton eliminarproveedor;
    private javax.swing.JTextField idcategoriaproductofield;
    private javax.swing.JTextField idclientefield;
    private javax.swing.JTextField idproductofield;
    private javax.swing.JTextField idproveedorfield;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton leercliente;
    private javax.swing.JButton leerproducto;
    private javax.swing.JButton leerproveedor;
    private javax.swing.JTextField nombreclientefield;
    private javax.swing.JTextField nombreproductofield;
    private javax.swing.JTextField nombreproveedorfield;
    private javax.swing.JTextField precioproductofield;
    private javax.swing.JTextField precioproveedorfield;
    private javax.swing.JTable proveedortabla;
    private javax.swing.JTable tablaproducto;
    private javax.swing.JTable tbTotalCategorias;
    private javax.swing.JTextField txtIdCategoria;
    private javax.swing.JTextField txtnombrecategoria;
    // End of variables declaration//GEN-END:variables
}
